[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
include = '\.pyi?$'

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder"]
build-function = "hatch_jupyter_builder.npm_builder"
[tool.hatch.version]

[project]
name = "mlops"
version = "0.0.1"